export const projects = [
    {
        project_name: "Project 1",
        project_link: "https://example.com/project1",
        technology_used: "HTML, CSS, JavaScript",
        duration: "3 months",
        responsibility: "Front-end development",
        short_description: "A web application for managing tasks",
    },
    {
        project_name: "Project 2",
        project_link: "https://example.com/project2",
        technology_used: "React, Node.js, MongoDB",
        duration: "6 months",
        responsibility: "Full-stack development",
        short_description: "An e-commerce platform",
    },
    {
        project_name: "Project 3",
        project_link: "https://example.com/project3",
        technology_used: "Angular, Express.js, MySQL",
        duration: "4 months",
        responsibility: "Back-end development",
        short_description: "A customer management system",
    },
    {
        project_name: "Project 4",
        project_link: "https://example.com/project4",
        technology_used: "Vue.js, Firebase",
        duration: "2 months",
        responsibility: "Front-end development",
        short_description: "A real-time chat application",
    },
    {
        project_name: "Project 5",
        project_link: "https://example.com/project5",
        technology_used: "Django, PostgreSQL",
        duration: "5 months",
        responsibility: "Full-stack development",
        short_description: "A blogging platform",
    },
    {
        project_name: "Project 6",
        project_link: "https://example.com/project6",
        technology_used: "React Native, Firebase",
        duration: "3 months",
        responsibility: "Mobile app development",
        short_description: "A social media app",
    },
    {
        project_name: "Project 7",
        project_link: "https://example.com/project7",
        technology_used: "ASP.NET, SQL Server",
        duration: "6 months",
        responsibility: "Back-end development",
        short_description: "An inventory management system",
    },
    {
        project_name: "Project 8",
        project_link: "https://example.com/project8",
        technology_used: "Flutter, Firebase",
        duration: "4 months",
        responsibility: "Mobile app development",
        short_description: "A task management app",
    },
    {
        project_name: "Project 9",
        project_link: "https://example.com/project9",
        technology_used: "Ruby on Rails, PostgreSQL",
        duration: "5 months",
        responsibility: "Full-stack development",
        short_description: "An online marketplace",
    },
    {
        project_name: "Project 10",
        project_link: "https://example.com/project10",
        technology_used: "Vue.js, Node.js, MongoDB",
        duration: "3 months",
        responsibility: "Full-stack development",
        short_description: "A recipe sharing platform",
    },
];


